/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectofinaledd.frontend.inicio;

import com.mycompany.proyectofinaledd.backend.Controlador;
import com.mycompany.proyectofinaledd.backend.exception.ExceptionBibliotecaMagica;
import com.mycompany.proyectofinaledd.backend.grafo.NodoGrafo;
import com.mycompany.proyectofinaledd.backend.listaenlazada.NodoListaEnlazadaDoble;
import com.mycompany.proyectofinaledd.frontend.agregarlibro.DialogAgregarLibro;
import com.mycompany.proyectofinaledd.frontend.busquedas.DialogBusquedaGenero;
import com.mycompany.proyectofinaledd.frontend.busquedas.DialogBusquedaIsbn;
import com.mycompany.proyectofinaledd.frontend.busquedas.DialogBusquedaRangoFechas;
import com.mycompany.proyectofinaledd.frontend.busquedas.DialogBusquedaTitulo;
import com.mycompany.proyectofinaledd.frontend.busquedas.DialogEliminarLibro;
import com.mycompany.proyectofinaledd.frontend.busquedas.DialogListarLibros;
import com.mycompany.proyectofinaledd.frontend.envios.DialogEnvios;
import javax.swing.JOptionPane;

/**
 *
 * @author brandon
 */
public class Inicio extends javax.swing.JFrame {

    private Controlador controlador;
    
    /**
     * Creates new form Inicio
     */
    public Inicio(Controlador controlador) {
        initComponents();
        this.setTitle("Biblioteca Mágica");
        this.controlador = controlador;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnBuscarPorTitulo = new javax.swing.JButton();
        btnBuscarPorISBN = new javax.swing.JButton();
        btnBusquedaGenero = new javax.swing.JButton();
        btnBusquedaRangoFechas = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        ListarLibros = new javax.swing.JButton();
        btnExportarLIbros = new javax.swing.JButton();
        btnAgregarLibro = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnGraficarEstructuras = new javax.swing.JButton();
        btnCargarArchivoLibros = new javax.swing.JButton();
        btnCargarArchivoBibliotecas = new javax.swing.JButton();
        btnCargarArchivoConexiones = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnBuscarPorTitulo.setText("Buscar por Titulo");
        btnBuscarPorTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPorTituloActionPerformed(evt);
            }
        });

        btnBuscarPorISBN.setText("Buscar por ISBN");
        btnBuscarPorISBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPorISBNActionPerformed(evt);
            }
        });

        btnBusquedaGenero.setText("Buscar por Genero");
        btnBusquedaGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBusquedaGeneroActionPerformed(evt);
            }
        });

        btnBusquedaRangoFechas.setText("Buscar por Rango de Fechas");
        btnBusquedaRangoFechas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBusquedaRangoFechasActionPerformed(evt);
            }
        });

        jButton6.setText("Eliminar Libro");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        ListarLibros.setText("Listar Libros por Titulo");
        ListarLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarLibrosActionPerformed(evt);
            }
        });

        btnExportarLIbros.setText("Exportar Libro entre Bibliotecas");
        btnExportarLIbros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarLIbrosActionPerformed(evt);
            }
        });

        btnAgregarLibro.setText("Agregar Libro");
        btnAgregarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarLibroActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 48)); // NOI18N
        jLabel1.setText("BIBLIOTECA MÁGICA");

        btnGraficarEstructuras.setText("Graficar Estructuras");
        btnGraficarEstructuras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraficarEstructurasActionPerformed(evt);
            }
        });

        btnCargarArchivoLibros.setText("Cargar Archivo .csv Libros");
        btnCargarArchivoLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarArchivoLibrosActionPerformed(evt);
            }
        });

        btnCargarArchivoBibliotecas.setText("Cargar Archivo .csv Bibliotecas");
        btnCargarArchivoBibliotecas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarArchivoBibliotecasActionPerformed(evt);
            }
        });

        btnCargarArchivoConexiones.setText("Cargar Archivo .csv Conexiones");
        btnCargarArchivoConexiones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarArchivoConexionesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(btnAgregarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscarPorTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscarPorISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnBusquedaGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnBusquedaRangoFechas, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(ListarLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnExportarLIbros))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnCargarArchivoBibliotecas, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCargarArchivoConexiones, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGraficarEstructuras, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCargarArchivoLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarPorTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarPorISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBusquedaGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBusquedaRangoFechas, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ListarLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnExportarLIbros, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnGraficarEstructuras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCargarArchivoBibliotecas, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnCargarArchivoLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCargarArchivoConexiones, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarLibroActionPerformed
        // TODO add your handling code here:
        DialogAgregarLibro ingresarLibro = new DialogAgregarLibro(this, false, this.controlador);
        ingresarLibro.setLocationRelativeTo(null);
        ingresarLibro.setVisible(true);
    }//GEN-LAST:event_btnAgregarLibroActionPerformed
        
    private void btnCargarArchivoBibliotecasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarArchivoBibliotecasActionPerformed
        // TODO add your handling code here:
        try {
            this.controlador.cargarBibliotecas();
        } catch (ExceptionBibliotecaMagica e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCargarArchivoBibliotecasActionPerformed

    private void btnCargarArchivoConexionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarArchivoConexionesActionPerformed
        // TODO add your handling code here:
        if (!controlador.isHayBibliotecas()) {
            JOptionPane.showMessageDialog(this, "No existen Bibliotecas aún", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            this.controlador.cargarConexiones();
        } catch (ExceptionBibliotecaMagica e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCargarArchivoConexionesActionPerformed

    private void btnCargarArchivoLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarArchivoLibrosActionPerformed
        // TODO add your handling code here:
        if (!this.controlador.isHayConexiones()) {
            JOptionPane.showMessageDialog(this, "No existen conexiones entre bibliotecas aún", "Error", JOptionPane.ERROR_MESSAGE);
        }
        try {
            this.controlador.cargarLibros();
        } catch (Exception e) {
            System.out.println("ERROR: " + e.getMessage());
        }
    }//GEN-LAST:event_btnCargarArchivoLibrosActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnGraficarEstructurasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraficarEstructurasActionPerformed
        // TODO add your handling code here:
        if (this.controlador.getLibros().getTamanio() == 0) {
            JOptionPane.showMessageDialog(this, "No se pueden generar las graficas aún", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        NodoListaEnlazadaDoble<NodoGrafo> actualGrafo = this.controlador.getGrafoBibliotecas().getNodosGrafo().getInicio();
        while (actualGrafo != null) {            
            actualGrafo.getDato().getBiblioteca().generarImagenesEstructuras();
            actualGrafo = actualGrafo.getSiguiente();
        }
        JOptionPane.showConfirmDialog(null, "Imagenes generadas en carpeta: imagenes", "Exito!", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnGraficarEstructurasActionPerformed

    private void btnBuscarPorTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPorTituloActionPerformed
        // TODO add your handling code here:
        DialogBusquedaTitulo buscarPorTitulo = new DialogBusquedaTitulo(this, false, this.controlador);
        buscarPorTitulo.setLocationRelativeTo(null);
        buscarPorTitulo.setVisible(true);
    }//GEN-LAST:event_btnBuscarPorTituloActionPerformed

    private void btnBuscarPorISBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPorISBNActionPerformed
        // TODO add your handling code here:
        DialogBusquedaIsbn busquedaIsbn = new DialogBusquedaIsbn(this, false, controlador);
        busquedaIsbn.setLocationRelativeTo(null);
        busquedaIsbn.setVisible(true);
    }//GEN-LAST:event_btnBuscarPorISBNActionPerformed

    private void btnBusquedaGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBusquedaGeneroActionPerformed
        // TODO add your handling code here:
        DialogBusquedaGenero buscarGenero = new DialogBusquedaGenero(this, false, controlador);
        buscarGenero.setLocationRelativeTo(null);
        buscarGenero.setVisible(true);
    }//GEN-LAST:event_btnBusquedaGeneroActionPerformed

    private void btnBusquedaRangoFechasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBusquedaRangoFechasActionPerformed
        // TODO add your handling code here:
        DialogBusquedaRangoFechas busquedaPorFechas = new DialogBusquedaRangoFechas(this, false, controlador);
        busquedaPorFechas.setLocationRelativeTo(null);
        busquedaPorFechas.setVisible(true);
    }//GEN-LAST:event_btnBusquedaRangoFechasActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        DialogEliminarLibro eliminarLibros = new DialogEliminarLibro(null, false, controlador);
        eliminarLibros.setLocationRelativeTo(null);
        eliminarLibros.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void ListarLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarLibrosActionPerformed
        // TODO add your handling code here:
        DialogListarLibros dialogListarLibros = new DialogListarLibros(null, true, controlador);
        dialogListarLibros.setLocationRelativeTo(null);
        dialogListarLibros.setVisible(true);
    }//GEN-LAST:event_ListarLibrosActionPerformed

    private void btnExportarLIbrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarLIbrosActionPerformed
        // TODO add your handling code here:
        DialogEnvios envios = new DialogEnvios(null, false, controlador);
        envios.setLocationRelativeTo(null);
        envios.setVisible(true);
    }//GEN-LAST:event_btnExportarLIbrosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ListarLibros;
    private javax.swing.JButton btnAgregarLibro;
    private javax.swing.JButton btnBuscarPorISBN;
    private javax.swing.JButton btnBuscarPorTitulo;
    private javax.swing.JButton btnBusquedaGenero;
    private javax.swing.JButton btnBusquedaRangoFechas;
    private javax.swing.JButton btnCargarArchivoBibliotecas;
    private javax.swing.JButton btnCargarArchivoConexiones;
    private javax.swing.JButton btnCargarArchivoLibros;
    private javax.swing.JButton btnExportarLIbros;
    private javax.swing.JButton btnGraficarEstructuras;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}