/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.proyectofinaledd.frontend.busquedas;

import com.mycompany.proyectofinaledd.backend.Controlador;
import com.mycompany.proyectofinaledd.backend.grafo.Biblioteca;
import com.mycompany.proyectofinaledd.backend.grafo.NodoGrafo;
import com.mycompany.proyectofinaledd.backend.libro.Libro;
import com.mycompany.proyectofinaledd.backend.listaenlazada.NodoListaEnlazadaDoble;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author brandon
 */
public class DialogBusquedaTitulo extends javax.swing.JDialog {

    private Controlador controlador;

    /**
     * Creates new form DialogBusquedaTitulo
     */
    public DialogBusquedaTitulo(java.awt.Frame parent, boolean modal, Controlador controlador) {
        super(parent, modal);
        initComponents();
        this.controlador = controlador;
        this.asignarBibliotecasDestinoOrigen();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtBuscarTitulo = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        txtResultado = new javax.swing.JTextField();
        comboBoxBibliotecaOrigen = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel1.setText("Buscar en biblioteca: ");

        jLabel2.setText("Titulo del libro: ");

        jLabel3.setText("Resultado o sugerencias");

        jLabel4.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel4.setText("Buscar por Titulo (Arbol AVL)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBuscarTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboBoxBibliotecaOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jLabel4)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscarTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxBibliotecaOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(btnBuscar)
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        String titulo = txtBuscarTitulo.getText().trim();
        this.txtResultado.setText("");

        if (titulo.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor ingresa un título.");
            return;
        }

        NodoListaEnlazadaDoble<NodoGrafo> bibliotecaEncontrada = this.obtenerBiblioteca();
        if (bibliotecaEncontrada != null) {
            Libro encontrado = bibliotecaEncontrada.getDato().getBiblioteca().getArbolAVL().buscarPorTitulo(titulo);
            if (encontrado != null) {
                txtResultado.setText("📖 Libro encontrado:\n"
                        + "Título: " + encontrado.getTitulo() + "\n"
                        + "Autor: " + encontrado.getAutor() + "\n"
                        + "Género: " + encontrado.getGenero() + "\n"
                        + "Fecha: " + encontrado.getAnio());
            } else {
                // Mostrar sugerencias
                List<Libro> sugerencias = bibliotecaEncontrada.getDato().getBiblioteca().getArbolAVL().sugerenciasPorTitulo(titulo);
                if (sugerencias.isEmpty()) {
                    txtResultado.setText("❌No se encontró ningún libro con ese título.");
                } else {
                    StringBuilder sb = new StringBuilder("🔍 No se encontró exactamente.\nSugerencias:\n\n");
                    for (Libro l : sugerencias) {
                        sb.append("- ").append(l.getTitulo()).append("\n");
                    }
                    txtResultado.setText(sb.toString());
                }
            }
        } else {
            JOptionPane.showConfirmDialog(null, "Error: biblioteca no encontrada");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void asignarBibliotecasDestinoOrigen() {
        NodoListaEnlazadaDoble<Biblioteca> actual = this.controlador.getBibliotecas().getInicio();
        while (actual != null) {
            this.comboBoxBibliotecaOrigen.addItem(actual.getDato().getId());
            actual = actual.getSiguiente();
        }
    }

    private NodoListaEnlazadaDoble<NodoGrafo> obtenerBiblioteca() {
        NodoListaEnlazadaDoble<NodoGrafo> actual = controlador.getGrafoBibliotecas().getNodosGrafo().getInicio();
        while (actual != null) {
            if (actual.getDato().getBiblioteca().getId().equals(this.comboBoxBibliotecaOrigen.getSelectedItem())) {
                return actual;
            }
            actual = actual.getSiguiente();
        }
        return null;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JComboBox<String> comboBoxBibliotecaOrigen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtBuscarTitulo;
    private javax.swing.JTextField txtResultado;
    // End of variables declaration//GEN-END:variables
}
