/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.proyectofinaledd.frontend.agregarlibro;

import com.mycompany.proyectofinaledd.backend.Controlador;
import com.mycompany.proyectofinaledd.backend.exception.ExceptionBibliotecaMagica;
import com.mycompany.proyectofinaledd.backend.grafo.Biblioteca;
import com.mycompany.proyectofinaledd.backend.grafo.NodoGrafo;
import com.mycompany.proyectofinaledd.backend.libro.Libro;
import com.mycompany.proyectofinaledd.backend.libro.TypeEstado;
import com.mycompany.proyectofinaledd.backend.listaenlazada.ListaEnlazadaDoble;
import com.mycompany.proyectofinaledd.backend.listaenlazada.NodoListaEnlazadaDoble;
import javax.swing.JOptionPane;

/**
 *
 * @author brandon
 */
public class DialogAgregarLibro extends javax.swing.JDialog {

    private Controlador controlador;

    /**
     * Creates new form DialogAgregarLibro
     */
    public DialogAgregarLibro(java.awt.Frame parent, boolean modal, Controlador controlador) {
        super(parent, modal);
        initComponents();
        this.controlador = controlador;
        this.asignarBibliotecasDestinoOrigen();
    }

    private boolean formularioValido() {
        if (this.cajaTextoAnio.getText().isBlank() || this.cajaTextoAnio.getText().isEmpty()) {
            return false;
        }
        if (this.cajaTextoAutor.getText().isBlank() || this.cajaTextoAutor.getText().isEmpty()) {
            return false;
        }
        if (this.cajaTextoGenero.getText().isBlank() || this.cajaTextoGenero.getText().isEmpty()) {
            return false;
        }
        if (this.cajaTextoISBN.getText().isBlank() || this.cajaTextoISBN.getText().isEmpty()) {
            return false;
        }
        if (this.cajaTextoTitulo.getText().isBlank() || this.cajaTextoTitulo.getText().isEmpty()) {
            return false;
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cajaTextoTitulo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cajaTextoAutor = new javax.swing.JTextField();
        cajaTextoAnio = new javax.swing.JTextField();
        cajaTextoISBN = new javax.swing.JTextField();
        cajaTextoGenero = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        comboBoxBibliotecaOrigen = new javax.swing.JComboBox<>();
        comboBoxBibliotecaDestino = new javax.swing.JComboBox<>();
        btnIngresarLibro = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        comboBoxPrioridad = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Titulo:");

        jLabel2.setText("Autor:");

        jLabel3.setText("ISBN:");

        jLabel4.setText("Año:");

        jLabel5.setText("Genero:");

        jLabel6.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabel6.setText("Agregar Libro");

        jLabel7.setText("Biblioteca Origen:");

        jLabel8.setText("Biblioteca Destino:");

        btnIngresarLibro.setText("Ingresar Libro");
        btnIngresarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarLibroActionPerformed(evt);
            }
        });

        jLabel9.setText("Prioridad:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(60, 60, 60)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cajaTextoTitulo)
                            .addComponent(cajaTextoAutor)
                            .addComponent(cajaTextoISBN)
                            .addComponent(cajaTextoAnio)
                            .addComponent(cajaTextoGenero)
                            .addComponent(comboBoxBibliotecaDestino, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboBoxBibliotecaOrigen, 0, 163, Short.MAX_VALUE)
                            .addComponent(comboBoxPrioridad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(btnIngresarLibro)))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel6)
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cajaTextoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cajaTextoAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cajaTextoISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cajaTextoAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cajaTextoGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(comboBoxBibliotecaOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(comboBoxBibliotecaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(comboBoxPrioridad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(btnIngresarLibro)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarLibroActionPerformed
        // TODO add your handling code here:
        Libro libroCreado;

        if (this.formularioValido()) {
            if (this.comboBoxPrioridad.getSelectedItem().equals("Tiempo")) {
                libroCreado = new Libro(this.cajaTextoTitulo.getText(), this.cajaTextoISBN.getText(), this.cajaTextoGenero.getText(),
                        Integer.valueOf(this.cajaTextoAnio.getText()), cajaTextoAutor.getText(), TypeEstado.EN_TRANSITO, true);
            } else {
                libroCreado = new Libro(this.cajaTextoTitulo.getText(), this.cajaTextoISBN.getText(), this.cajaTextoGenero.getText(),
                        Integer.valueOf(this.cajaTextoAnio.getText()), cajaTextoAutor.getText(), TypeEstado.EN_TRANSITO, false);
            }

            Biblioteca origen = this.controlador.getGrafoBibliotecas().getBibliotecaPorId(comboBoxBibliotecaOrigen.getSelectedItem().toString());
            Biblioteca destino = this.controlador.getGrafoBibliotecas().getBibliotecaPorId(comboBoxBibliotecaDestino.getSelectedItem().toString());

            libroCreado.setBibliotecaOrigen(origen);
            libroCreado.setBibliotecaDestino(destino);

            NodoListaEnlazadaDoble<NodoGrafo> actualNodoGrafo = this.controlador.getGrafoBibliotecas().getNodosGrafo().getInicio();
            while (actualNodoGrafo != null) {
                //Condicional para verificar si la biblioteca origen del libro coincide con alguna de las del grafo
                if (libroCreado.getBibliotecaDestino().getId().equals(actualNodoGrafo.getDato().getBiblioteca().getId())) {
                    actualNodoGrafo.getDato().getBiblioteca().getArbolAVL().insertar(libroCreado);
                    actualNodoGrafo.getDato().getBiblioteca().getArbolB().insert(libroCreado);
                    actualNodoGrafo.getDato().getBiblioteca().getArbolBMas().insertar(libroCreado);
                    actualNodoGrafo.getDato().getBiblioteca().getTablaHash().insertar(libroCreado);
                    actualNodoGrafo.getDato().getBiblioteca().getListaEnlazada().agregarValorAlFinal(libroCreado);
                    break;
                }
                actualNodoGrafo = actualNodoGrafo.getSiguiente();
            }
            String ruta;
            
            if (libroCreado.isPrioridadTiempo()) {
                ListaEnlazadaDoble<Biblioteca> rutaTiempo = this.controlador.getGrafoBibliotecas().dijkstra(
                        libroCreado.getBibliotecaOrigen().getId(), libroCreado.getBibliotecaDestino().getId(), true);
                ruta = this.mostrarRuta(rutaTiempo);
                JOptionPane.showMessageDialog(null, "Ruta" + ruta + "\nTiempo: "
                        + this.controlador.getGrafoBibliotecas().calcularTotalRuta(rutaTiempo, true),
                        "Libro guardado con exito", JOptionPane.INFORMATION_MESSAGE);
            } else {
                ListaEnlazadaDoble<Biblioteca> rutaCosto = this.controlador.getGrafoBibliotecas().dijkstra(
                        libroCreado.getBibliotecaOrigen().getId(), libroCreado.getBibliotecaDestino().getId(), false);
                JOptionPane.showMessageDialog(
                        null,
                        "Ruta: " + String.valueOf(this.mostrarRuta(rutaCosto))
                        + "\nCosto: " + this.controlador.getGrafoBibliotecas()
                                .calcularTotalRuta(rutaCosto, false),
                        "Libro guardado con exito",
                        JOptionPane.INFORMATION_MESSAGE
                );
                /*
                JOptionPane.showMessageDialog(null, "Ruta"+this.mostrarRuta(rutaCosto) + "\nCosto: "
                        + this.controlador.getGrafoBibliotecas().calcularTotalRuta(rutaCosto, false),
                        "Libro guardado con exito", JOptionPane.INFORMATION_MESSAGE);
                 */
            }
            return;

        }
        JOptionPane.showMessageDialog(null, "Error en el formulario", "Error", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_btnIngresarLibroActionPerformed

    private void asignarBibliotecasDestinoOrigen() {
        NodoListaEnlazadaDoble<Biblioteca> actual = this.controlador.getBibliotecas().getInicio();
        while (actual != null) {
            this.comboBoxBibliotecaOrigen.addItem(actual.getDato().getId());
            this.comboBoxBibliotecaDestino.addItem(actual.getDato().getId());
            actual = actual.getSiguiente();
        }
        this.comboBoxPrioridad.addItem("Tiempo");
        this.comboBoxPrioridad.addItem("Costo");
    }

    private String mostrarRuta(ListaEnlazadaDoble<Biblioteca> ruta) {
        String rutaOptima = "";
        if (ruta.getTamanio() == 0) {
            System.out.println("No hay ruta disponible.");
            return null;
        }
        NodoListaEnlazadaDoble<Biblioteca> actual = ruta.getInicio();
        while (actual != null) {
            System.out.print(actual.getDato().getId());
            rutaOptima = rutaOptima + actual.getDato().getId();
            if (actual.getSiguiente() != null) {
                System.out.print(" --> ");
                rutaOptima = rutaOptima + " --> ";
            }
            actual = actual.getSiguiente();
        }
        System.out.println();
        return rutaOptima;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresarLibro;
    private javax.swing.JTextField cajaTextoAnio;
    private javax.swing.JTextField cajaTextoAutor;
    private javax.swing.JTextField cajaTextoGenero;
    private javax.swing.JTextField cajaTextoISBN;
    private javax.swing.JTextField cajaTextoTitulo;
    private javax.swing.JComboBox<String> comboBoxBibliotecaDestino;
    private javax.swing.JComboBox<String> comboBoxBibliotecaOrigen;
    private javax.swing.JComboBox<String> comboBoxPrioridad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
